services:
  web:
    build:
      context: .
      target: prod
    container_name: portfolio-client
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true